name: Build and Release re:Alive

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch: {}

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            buildCommand: "npm run build:linux"
            artifactName: "reAlive-linux.zip"
          - os: macos-latest
            buildCommand: "npm run build:mac"
            artifactName: "reAlive-macos.zip"
          - os: windows-latest
            buildCommand: "npm run build:win"
            artifactName: "reAlive-windows.zip"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust if needed

      - name: Install Dependencies
        run: npm ci

      - name: Run Build Command
        run: ${{ matrix.buildCommand }}

      # Assuming electron-builder outputs the packaged app into the "dist" folder.
      # Adjust the path below if your build produces the artifact elsewhere.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: dist/
  
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: reAlive-linux.zip
          path: artifacts/linux

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: reAlive-macos.zip
          path: artifacts/macos

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: reAlive-windows.zip
          path: artifacts/windows

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            This release contains builds for Linux, Windows, and macOS.

      - name: Upload Linux Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/linux
          asset_name: reAlive-linux.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/macos
          asset_name: reAlive-macos.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Artifact to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/windows
          asset_name: reAlive-windows.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
